version: '3.5'

networks:
  sun-application:
    name: sun-application

services:
  sun-app:
    build: .
    container_name: sun-app
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "5000:80"
    networks:
      - sun-application
    hostname: api
    domainname: elosun.test

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - sun-application
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elosun-db
    ports:
      - "8080:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql

